<div class="settings">
	<div class="label"><?php echo __( 'Settings', 'thrive-cb' ); ?></div>

	<div class="tve-settings-email"></div>
</div>

<div class="advanced-settings">
	<p class="tve-toggle tve-as-title"><?php echo __( 'Advanced', 'thrive-cb' ); ?></p>

	<div class="tve-advanced-settings-email tcb-hide"></div>
</div>

<div class="tve-email-content">

	<div class="tve-message-settings-email"></div>
</div>

<div class="tve-email-include-data">
	<div class="label"><?php echo __( 'Include', 'thrive-cb' ); ?></div>

	<div class="tve-include-settings-email"></div>
</div>
