<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tva-main-cover-style-w-img">
	<div style='width: 100%; background-image:url("<#= model.get('cover_image') #>");' class="tva-course-image-holder">
	<span class="tva-remove-lesson-cover-image"><?php _e( 'Remove Image', TVA_Const::T ) ?></span>
</div>