<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tvd-card tvd-red tvd-xsmall">
	<div class="tvd-card-content tva-lesson-del">
		<div class="tvd-row">
			<div class="tvd-col tvd-s8">
				<h4 class="tvd-margin-top">
					<?php echo __( 'Are you sure you want to delete this lesson?', TVA_Const::T ) ?>
				</h4>
			</div>
			<div class="tvd-col tvd-s2">
				<a class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-left tva-delete-no">
					<?php echo __( 'Cancel', TVA_Const::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s2">
				<a class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-light tvd-right tva-delete-yes">
					<?php echo __( 'Delete', TVA_Const::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>