<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="clearfix">
	<input class="tva-bundle-change" id="tva-<#= tag #>-bundle-<#= model.get('id') #>" type="checkbox" value="<#= model.get('id') #>" <#= checked && checked.length > 0 && checked.indexOf(model.get('id')) !== -1 ? 'checked="checked"' : '' #> />
	<label for="tva-<#= tag #>-bundle-<#= model.get('id') #>">
		<#= model.get('name') #>
	</label>
</div>
