<div class="fr-dynamic-box fr-link-box" style="display:none">
	<div class="fr-action-buttons row between-xs reverse">
		<div class="fr-dynamic-categories w-100">
			<?php echo tcb_template( 'controls/link/dynamic-categories.phtml', null, true, 'backbone' ) ?>
		</div>
		<div class="fr-dynamic-links w-100">
			<?php echo tcb_template( 'controls/link/dynamic-links.phtml', null, true, 'backbone' ) ?>
		</div>

		<div class="fr-checkbox-line fr-link-atts w-100">
			<span class="fr-checkbox"><input name="target" class="fr-link-attr" data-checked="_blank" type="checkbox" id="fr-link-target"><span><?php tcb_icon( 'froala-checkmark' ); ?></span></span><label for="fr-link-target"><?php echo __( 'Open in new tab', 'thrive-cb' ) ?></label>
			<span class="fr-checkbox"><input name="rel" class="fr-link-attr" data-checked="nofollow" type="checkbox" id="fr-link-rel"><span><?php tcb_icon( 'froala-checkmark' ); ?></span></span><label for="fr-link-rel"><?php echo __( 'Nofollow', 'thrive-cb' ) ?></label>
		</div>
		<button class="fr-command fr-submit" role="button" data-cmd="dynamicLinkInsert" href="#" type="button"><?php echo __( 'Insert', 'thrive-cb' ) ?></button>
		<button class="fr-command fr-danger fr-remove fr-hidden" role="button" data-cmd="dynamicLinkRemove" href="#" type="button"><?php echo __( 'Remove', 'thrive-cb' ) ?></button>
	</div>
</div>