<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tva-main-cover-style-w-img">
	<div class="tva-author-custom-img" style='background-image:url("<#= model.get('url') #>");' class="tva-author-image-holder">
		<span class="tva-remove-author-cover-image"><?php _e( 'Remove Image', TVA_Const::T ) ?></span>
	</div>
</div>
