<p><?php echo __( 'Give access if user has:', 'thrive-apprentice' ) ?></p>
<div class="tva-integrations-list"></div>
<div class="tva-integration-items"></div>
<button class="click tva-integration-cancel" data-fn="cancel"><?php echo __( 'Cancel', 'thrive-apprentice' ) ?></button>
<button class="click tva-integration-save" data-fn="save"><?php echo __( 'Add Rule', 'thrive-apprentice' ) ?></button>

