<div class="tva-sendowl-notice">
	<div class="tva-warning tva-notice-extra">
		<span class="svg-container"><?php tva_get_svg_icon( 'info-icon' ); ?></span>
		<h3><?php echo __( 'Checkout Page Not Set', 'thrive-apprentice' ) ?></h3>
		<p>
			<?php
			$url  = get_admin_url() . 'admin.php?page=tva_dashboard#sendowl_checkout';
			$text = "The checkout page hasn't been set. %s to set it.";

			echo sprintf( $text, '<a href="' . $url . '">' . __( 'Click here', 'thrive-apprentice' ) . '</a>' );

			?>
			<?php echo __( ' Please make sure to save the current course settings in order not to lose the current progress.', 'thrive-apprentice' ) ?>
		</p>
	</div>
</div>
