<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<h3 class="tvd-title" id="tva-course-topic"><?php echo __( 'Label management', TVA_Const::T ) ?></h3>
<a href="javascript:void(0)" class="tvd-btn tvd-btn-blue tvd-waves-light tva-add-label"> <?php echo __( 'Add New', TVA_Const::T ) ?> </a>
<div class="tvd-v-spacer"></div>
<div class="tva-topic-wrapper clearfix" id="tva-labels-collection"></div>

<div class="">
	<a class="back-to-the-dashboard" href="#dashboard">&lt;&nbsp;<?php echo __( 'Back to Dashboard', TVA_Const::T ) ?></a>
</div>

