<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>
<div class="clearfix">
	<div class="tvd-collection-header">
		<div class="tva-floating tva-topic-title-holder">
			<span>
				<?php echo __( 'Title', TVA_Const::T ) ?>
			</span>
		</div>
		<div class="tva-floating tva-topic-color-holder">
			<span>
				<?php echo __( 'Color', TVA_Const::T ) ?>
			</span>
		</div>
		<div class="tva-floating tva-topic-remove-holder"
			<span>
				<?php echo __( 'Actions', TVA_Const::T ) ?>
			</span>
		</div>
	</div>
</div>
