<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<h3 class="tva-sendowl-settings tva-checkout-h"><?php echo __( 'Login Page', TVA_Const::T ) ?></h3>

<div class="tva-checkout-container">

	<div class="tva-api-settings">
		<div class="tva-login-page-container" ></div>
	</div>

</div>

<a class="back-to-the-dashboard" href="#dashboard">&lt;&nbsp;<?php echo __( 'Back to Dashboard', TVA_Const::T ) ?></a>
