<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>
<div class="clearfix">
	<div class="tvd-collection-header">
		<div class="tva-floating tva-topic-title-holder">
			<span>
				<?php echo __( 'Title', TVA_Const::T ) ?>
			</span>
		</div>
		<div class="tva-floating tva-topic-icon-holder">
			<span>
				<?php echo __( 'Topic Icon', TVA_Const::T ) ?>
				<i class="tva-info-icon">
					i
					<span class="tva-status-tooltip"><?php echo __( 'The recommended size is 32 x 32 px', TVA_Const::T ) ?></span>
				</i>
			</span>
		</div>
		<div class="tva-floating tva-topic-color-holder">
			<span>
				<?php echo __( 'Topic Color', TVA_Const::T ) ?>
			</span>
		</div>
		<div class="tva-floating tva-topic-color-holder ">
			<span>
				<?php echo __( 'Icon Color', TVA_Const::T ) ?>
			</span>
			<div>
				<span>
					<?php echo __( 'Course Overview', TVA_Const::T ) ?>
				</span>
				<span>
					<?php echo __( 'Course Layout', TVA_Const::T ) ?>
				</span>
			</div>
		</div>
		<div class="tva-floating tva-topic-color-holder ">
			<span>
				<?php echo __( 'Preview', TVA_Const::T ) ?>
			</span>
			<div>
				<span>
					<?php echo __( 'Course Overview', TVA_Const::T ) ?>
				</span>
				<span>
					<?php echo __( 'Course Layout', TVA_Const::T ) ?>
				</span>
			</div>
		</div>
		<div class="tva-floating tva-topic-remove-holder">
			<span>
				<?php echo __( 'Actions', TVA_Const::T ) ?>
			</span>
		</div>
</div>

