<div class="control-grid full-width pb-0">
	<span>
	<?php esc_attr_e( 'Unable to map fields because there is no Autoresponder connected or the current one does not support it.' ) ?>
	</span>
	<a class="blue-text" href="//thrivethemes.com/tkb_item/what-autoresponders-does-the-custom-field-integration-with-the-lead-generation-element-support/" target="_blank">
		<?php echo __( 'Learn more about this.', 'thrive-cb' ) ?>
	</a>
</div>