<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<h3 class="tva-sendowl-settings"><?php echo __( 'Create products in SendOwl', 'thrive-apprentice' ) ?></h3>

<div class="tva-sendowl-guide">
	<div class="tva-sendowl-step">
		<div class="tva-step-title">
			<div class="tva-step-nr">1</div>
			<div class="tva-title">
				<p>
					<?php
					echo sprintf(
						__( 'Log into your %s account', 'thrive-apprentice' ),
						'<a href="https://www.sendowl.com/" target="_blank">SendOwl</a>'
					);
					?>
				</p>
			</div>
		</div>

		<img src="<?php echo TVA_Const::plugin_url( 'admin/img/sendowl-guide1.jpg' ); ?>" class="sendowl-step-img" />
	</div>

	<div class="tva-sendowl-step">
		<div class="tva-step-title">
			<div class="tva-step-nr">2</div>
			<div class="tva-title">
				<p>
					<?php
					echo sprintf(
						__( 'Go to the right sidebar menu and select %s', 'thrive-apprentice' ),
						'<a class="sendowl-step-spl" href="https://www.sendowl.com/products" target="_blank">Products</a>'
					);
					?>
				</p>
			</div>
		</div>

		<div class="tva-step-content tva-hide"></div>
	</div>

	<div class="tva-sendowl-step">

		<div class="tva-step-title">
			<div class="tva-step-nr">3</div>
			<div class="tva-title">
				<span><?php echo __( 'Copy this URL' ); ?></span>
				<div class="tva-copy-container">
					<input class="tva-so-thankyou-page" type="text" readonly value="<#= ThriveApp.globals.settings.get( 'thankyou_endpoint' ) #>">
					<button class="tva-sendowl-search">
						<span class="tva-status-tooltip"><?php echo __( 'Copy', TVA_Const::T ) ?></span>
					</button>
				</div>
			</div>
		</div>

		<div class="tva-step-content tva-hide"></div>
	</div>

	<div class="tva-sendowl-step">
		<div class="tva-step-title">
			<div class="tva-step-nr">4</div>
			<div class="tva-title">
				<p>
					<?php
					echo sprintf(
						__( 'Press %s button and choose %s', 'thrive-apprentice' ),
						'<strong>Add Product</strong>',
						'<strong>Product</strong>'
					);
					?>
				</p>
			</div>
		</div>

		<img src="<?php echo TVA_Const::plugin_url( 'admin/img/sendowl-guide2.jpg' ); ?>" class="sendowl-step-img" />
	</div>

	<div class="tva-sendowl-step">
		<div class="tva-step-title">
			<div class="tva-step-nr">5</div>
			<div class="tva-title">
				<p>
					<?php
					echo sprintf(
						__( 'Choose %s. Add product %s and %s. Paste the URL from step 3. Press %s button', 'thrive-apprentice' ),
						'<strong>Redirect</strong>',
						'<strong>Name</strong>',
						'<strong>Price</strong>',
						'<strong>Create Product</strong>'
					);
					?>
				</p>
			</div>
		</div>

		<img src="<?php echo TVA_Const::plugin_url( 'admin/img/sendowl-guide3.jpg' ); ?>" class="sendowl-step-img" />
	</div>

	<div class="tva-sendowl-step">
		<div class="tva-step-title">
			<div class="tva-step-check"></div>
			<div class="tva-title">
				<p>
					<?php echo __( 'That’s it, your product is created. Repeat the process to create more products to sell', 'thrive-apprentice' ); ?>
				</p>
			</div>
		</div>
	</div>
</div>

<a class="back-to-the-dashboard btd-extra" href="#sendowl_quick_start">&lt;&nbsp;<?php echo __( 'Back to Settings', TVA_Const::T ) ?></a>
