<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="one-course-purchase">
	<h3 class="blue-h3"><?php echo __( 'For one course purchased', 'thrive-apprentice' ) ?></h3>
	<p><?php echo __( 'What purchase confirmation message would you like to display to the visitor?', 'thrive-apprentice' ) ?></p>
	<p><?php echo __( 'You can leave the field blank if you don\'t want to display a message', 'thrive-apprentice' ) ?></p>
	<p><a href="<#= preview #>" target="_blank">
		<?php echo __( 'What does this message look like?', 'thrive-apprentice' ); ?>
	</a></p>

	<textarea id="tva-thankyou-message"></textarea>
</div>

<div class="tva-thankyou-page-multiple"></div>
