<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<h3><?php echo __( 'What page is your Checkout Page? ', TVA_Const::T ) ?></h3>
<p class="sendowl-p"><?php echo __( 'This is the general Checkout page for all your SendOwl products. This is where your customers will create their user account to access the course.', TVA_Const::T ) ?></p>

<p class="sendowl-p">
	<a href="//fast.wistia.net/embed/iframe/ibqm3k93n0?popover=true" class="wistia-popover[height=450,playerColor=2bb914,width=800]">
		<?php echo __( 'Click here to learn more about the Checkout Page.', TVA_Const::T ) ?>
	</a>
</p>

<div class="tva-checkout-div">
	<input id="tva-sendowl-checkout-page" placeholder="<?php echo __( 'Search page&hellip;', TVA_Const::T ) ?>" class="tvd-save tva-sendowl-input"
	       type="text" value="<#= model.get('checkout_page').name #>" data-field="checkout_page">

	<a href="<#= model.get('checkout_tcb_edit_url') #>" target="_blank" class="tva-sendowl-button-simple">
		<span><?php tva_get_svg_icon( 'pen' ); ?></span>
		<?php echo __( 'Edit Page', TVA_Const::T ) ?>
	</a>
</div>

<span class="tva-sep"><?php echo __( 'or ', TVA_Const::T ) ?></span>

<a href="javascript:void(0)" class="tva-sendowl-button tva-create-checkout-page"><?php echo __( 'Create a new page', TVA_Const::T ) ?></a>

<div id="tva-create-checkout-page" style="display: none;">
	<input id="tva-new-sendowl-checkout-page" type="text" placeholder="<?php echo __( 'Page Title', TVA_Const::T ) ?>" class="tva-sendowl-input tvd-save"
	       data-field="checkout_new_page">
	<a href="javascript:void(0)" class="tva-sendowl-button tva-create-checkout-page-submit"><?php echo __( 'Create page', TVA_Const::T ) ?></a>
</div>
