<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tva-modal-header">
	<h3 class="tvd-modal-title"><?php echo __( 'Add New Customer', TVA_Const::T ) ?></h3>
	<span class="tva-modal-next-step tva-bulk-import-button"><?php tva_get_svg_icon( 'cloud-download' ); ?><?php echo __( 'Bulk import' ) ?></span>
</div>

<div class="tva-modal-content tva-new-customer">
	<div class="tva-mr">
		<div class="tva-name-label tvd-input-field">
			<input id="tva-customer-name" type="text" placeholder="<?php echo __( 'Name', TVA_Const::T ) ?>" value="<#= model.get('user_login') #>"
			       data-field="user_login">
			<label for="tva-customer-name" class="tva-custom-label"><?php echo __( 'Name', TVA_Const::T ) ?></label>
		</div>
	</div>
	<div class="">
		<div class="tva-email-label tvd-input-field">
			<input id="tva-customer-email" type="text" placeholder="<?php echo __( 'Email', TVA_Const::T ) ?>"
			       value="<#= model.get('user_email') #>" data-field="user_email">
			<label for="tva-customer-email" class="tva-custom-label"><?php echo __( 'Email' ) ?></label>
		</div>
	</div>

	<p class="mb-small mt-clear"><?php echo __( 'Give users access to the following:', TVA_Const::T ) ?></p>

	<div class="tva-mr">
		<p class="mb-small"><?php echo __( 'Products', TVA_Const::T ) ?></p>

		<div class="tva-modal-card tva-sendowl-products"></div>
	</div>

	<div class="">
		<p class="mb-small"><?php echo __( 'Bundles', TVA_Const::T ) ?></p>

		<div class="tva-modal-card tva-sendowl-bundles"></div>
	</div>
</div>

<button type="button" class="tvd-modal-close"><?php echo __( 'Cancel', TVA_Const::T ) ?></button>
<button type="button" class="tvd-right tvd-modal-submit"><?php echo __( 'Continue', TVA_Const::T ) ?></button>

