<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package local.thrivethemes.com
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>
<div class="clearfix ttw-title-holder">
	<span class="tvd-title"><strong><?php echo __( 'Product:', TVA_Const::T) ?></strong><#= model.get('product') #></span>
	<span class="tvd-title"><strong><?php echo __( 'Type:', TVA_Const::T) ?></strong><#= model.get('type') #></span>
	<span class="tvd-title"><strong><?php echo __( 'Added:', TVA_Const::T) ?></strong> <#= model.get('date') #></span>
</div>

<div class="tve-debug-table"></div>
