<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php echo __( 'Are you sure you want to Delete these Items?', TVA_Const::T ) ?></h3>
	<p><?php echo __( 'You are about to delete the selected items and all content. This action cannot be undone.', TVA_Const::T ) ?></p>

	<div class="tva-modal-footer">
		<button type="button" class="tvd-modal-close"><?php echo __( 'Cancel', TVA_Const::T ) ?></button>
		<button type="button" class="tvd-modal-submit tvd-right"><?php echo __( 'Delete Items', TVA_Const::T ) ?></button>
	</div>
</div>




