<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php echo __( 'No Courses to move to!', TVA_Const::T ) ?></h3>
	<p><?php echo __( 'It seems that you only have this course set up. There are no other courses you can move your lessons to.', TVA_Const::T ) ?></p>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m12">
			<a href="javascript:void(0)"
			   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close tvd-right">
				<?php echo __( 'Close', TVA_Const::T ) ?>
			</a>
		</div>
	</div>
</div>