<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>
<div class="tvd-modal-content">
	<h3 class="tvd-modal-title"><?php echo __( 'Warning: You are about to delete the selected topic', TVA_Const::T ) ?></h3>
	<p><?php echo __( 'You are about to permanently delete a topic. Are you sure you want to delete it? ', TVA_Const::T ) ?></p>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close tva-white">
				<?php echo __( 'Cancel', TVA_Const::T ) ?>
			</a>
		</div>
		<div class="tvd-col tvd-s12 tvd-m6">
			<a href="javascript:void(0)"
			   class="tvd-btn tvd-btn-red tvd-waves-light tvd-right tva-confirm-delete">
				<?php echo __( 'Delete topic', TVA_Const::T ) ?>
			</a>
		</div>
	</div>
</div>