<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tva-modal-step tva-wizard-modal">
	<div class="tvd-modal-content">
		<h3 class="tvd-modal-title">
			<?php echo __( 'Welcome to Thrive Apprentice 2.0!', TVA_Const::T ) ?>
		</h3>
		<p class="tva-modal-description">
			<?php echo __( 'In order to create your online teaching platform, we need to set up a few things really quickly.', TVA_Const::T ) ?>
		</p>
		<p>
			<strong>
				<?php echo __( 'Step 1: ', TVA_Const::T ) ?>
			</strong>
			<?php echo __( 'Choose a page where all your courses will reside.', TVA_Const::T ) ?>
		</p>
		<div class="tvd-row tvd-collapse">
			<div class="tvd-col tvd-s12">
				<div class="tvd-input-field">
					<input id="tva-apprentice-page" class="tvd-save" type="text" value="<# model.get('index_page').name #>" data-field="index_page">
					<label for="tva-apprentice-page">
						<?php echo __( 'Courses Page (search through the pages)', TVA_Const::T ) ?>
					</label>
				</div>
			</div>
		</div>

		<p>
			<?php echo __( 'Or create a new page', TVA_Const::T ) ?>
		</p>
		<div class="tvd-row tvd-collapse">
			<div class="tvd-col tvd-s12">
				<div class="tvd-input-field">
					<input id="tva-new-apprentice-page" class="tvd-save" type="text" data-field="index_new_page">
					<label for="tva-new-apprentice-page">
						<?php echo __( 'Type the page name', TVA_Const::T ) ?>
					</label>
				</div>
			</div>
		</div>
		<div class="tvd-modal-footer">
			<a href="<?= admin_url() . '?page=tve_dash_section' ?>"
			   class="tvd-left tva-btn-gray">
				<?php echo __( 'Cancel', TVA_Const::T ) ?>
			</a>

			<a href="javascript:void(0)"
			   class="tvd-right tvd-modal-submit tva-btn-green tva-go-to-templates">
				<?php echo __( 'Continue', TVA_Const::T ) ?>
			</a>
		</div>
	</div>
</div>

<div class="tva-modal-step tva-wizard-modal-two">
	<div class="tvd-modal-content tva-choose-template">
		<h3 class="tvd-modal-title"><?php echo __( 'Template Setup', TVA_Const::T ) ?></h3>
		<p><strong><?php echo __( 'Step 2: ', TVA_Const::T ) ?></strong><?php echo __( 'You can choose to personalize the template for your courses or go directly to creating courses by loading the default template.', TVA_Const::T ) ?></p>
		<p><?php echo __( 'You can always edit the course template by going to ', TVA_Const::T ) ?><strong><?php echo __( 'Settings > Template Settings ', TVA_Const::T ) ?></strong>.</p>
	</div>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-col tvd-s2">
				<a href="javascript:void(0)"
				   class="tva-btn-gray tvd-left tva-modal-prev-step">
					<?php echo __( 'Back', TVA_Const::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s5 tva-personalize-button">
				<a href="javascript:void(0)"
				   class="tva-btn-blue tvd-right tva-go-to-wizard">
					<?php echo __( 'Personalize Template', TVA_Const::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s5 tva-default-button">
				<a href="javascript:void(0)"
				   class="tva-btn-blue tvd-right tva-go-to-dashboard">
					<?php echo __( 'Load Default Template', TVA_Const::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
