<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tvd-modal-content tva-import">
	<h3 class="tvd-modal-title"><?php echo __( 'Import Lessons', TVA_Const::T ) ?></h3>
	<p>
		<strong><?php echo __( 'Step 3: ', TVA_Const::T ) ?></strong>
		<?php echo __( 'The Theme Apprentice is Enabled. Would you like to import the existing courses and lessons in the old apprentice ?', TVA_Const::T ) ?>
	</p>
	<p>
		<?php echo __( 'You can always import apprentice lessons by going to ', TVA_Const::T ) ?><strong><?php echo __( 'Settings > Import ', TVA_Const::T ) ?></strong>.
	</p>
</div>
<div class="tvd-modal-footer">
	<div class="tvd-row">
		<div class="tvd-col tvd-s6">
			<a href="javascript:void(0)"
			   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-left tva-no">
				<?php echo __( 'Import later', TVA_Const::T ) ?>
			</a>
		</div>
		<div class="tvd-col tvd-s6">
			<a href="javascript:void(0)"
			   class="tvd-btn tvd-btn-green tvd-waves-light tvd-right tva-yes">
				<?php echo __( 'Import lessons', TVA_Const::T ) ?>
			</a>
		</div>
	</div>
</div>