<div class="tvd-row">
	<div class="tvd-col tvd-s12 tvd-m6">
		<a href="javascript:void(0)"
		   class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-dark tvd-waves-effect tvd-modal-close">
			<?php echo __( 'Cancel', TVA_Const::T ) ?>
		</a>
	</div>
	<div class="tvd-col tvd-s12 tvd-m6">
		<a href="javascript:void(0)"
		   class="tvd-btn tvd-btn-green tvd-waves-light tvd-right tvd-save tvd-modal-submit-content">
			<?php echo __( 'Continue', TVA_Const::T ) ?>
		</a>
	</div>
</div>