<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tva-modal-footer">
	<button type="button" class="tvd-waves-effect tvd-waves-light tvd-btn-flat tvd-btn-flat-primary tvd-gray tva-delete-no"><?php echo __( 'No', TVA_Const::T ) ?></button>
	<button type="button" class="tvd-waves-effect tvd-waves-light tvd-btn-flat tvd-red tvd-btn-flat-primary tvd-btn-flat-light tva-delete-yes tvd-right"><?php echo __( 'Yes', TVA_Const::T ) ?></button>
</div>