<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tvd-modal-content tva-wizard-professor">
	<h3 class="tvd-modal-title"><?php echo __( 'Hi there, Professor', TVA_Const::T ) ?></h3>
	<p><?php echo __( 'Since this is your first time using Thrive Apprentice, we will provide you with demo content in order to see which elements of the template are affected by the changes you make.', TVA_Const::T ) ?></p>
	<p><?php echo __( 'Don\'t worry! You\'ll still be able to change the preview to see your content by switching between DEMO and LIVE tabs.', TVA_Const::T ) ?></p>
	<div class="tvd-modal-footer">
		<div class="tvd-row">
			<div class="tvd-center tvd-col tvd-s12 tvd-m12">
				<a href="javascript:void(0)"
				   class="tvd-modal-close tva-btn-green">
					<?php echo __( 'Ok', TVA_Const::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>