<div id="tva-register-url" style="margin-top: 15px">
	<div class="tvd-input-field">
		<input id="tva-apprentice-register-page" type="text" value="<#= model.get('register_page').name ? model.get('register_page').name : '' #>" data-field="register_page" placeholder="<?php echo __( 'Search for the page', TVA_Const::T ) ?>">
		<label for="tva-apprentice-register-page"><?php echo __( 'Apprentice Register Page', TVA_Const::T ) ?></label>
	</div>
</div>