<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tva-modal-footer tva-modal-footer-main">
	<button type="button" class="tva-modal-prev-step"><?php echo __( 'Back', TVA_Const::T ) ?></button>
	<button type="button" class="tvd-right tvd-modal-submit"><?php echo __( 'Save', TVA_Const::T ) ?></button>
</div>
