<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<h3 class="tvd-modal-title"><?php echo __( 'Are you sure you want to Delete this Chapter?', TVA_Const::T ) ?></h3>

<p><?php echo __( 'You are about to delete the selected chapter and all content contained inside. This action cannot be undone.',  TVA_Const::T ) ?></p>