<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<h3 class="sendowl-h"><?php echo __( 'No Discounts Found', TVA_Const::T ) ?></h3>
<p class="sendowl-p"><?php echo __( 'We managed to connect to your SendOwl account but didn\'t find any discounts', TVA_Const::T ) ?>.
	<a href="https://thrivethemes.com/tkb_item/how-to-apply-discounts-to-your-products-bundles/"
	   target="_blank"><?php echo __( 'Click here to troubleshoot', TVA_Const::T ) ?></a>
</p>
