<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tvd-card tvd-red tvd-large tvd-slim-card tva-delete-course-card">
	<div class="tvd-card-content">
		<h4 class="tvd-margin-top">
			<?php echo __( 'Are you sure you want to delete this course?', TVA_Const::T ) ?>
		</h4>
	</div>
	<div class="tvd-card-action">
		<div class="tvd-row">
			<div class="tvd-col tvd-s12 tvd-m6 tvd-no-padding">
				<a class="tvd-btn-flat tvd-btn-flat-primary tvd-btn-flat-light tvd-left tva-delete-no">
					<?php echo __( 'CANCEL', TVA_Const::T ) ?>
				</a>
			</div>
			<div class="tvd-col tvd-s12 tvd-m6 tvd-no-padding">
				<a class="tvd-btn-flat tvd-btn-flat-secondary tvd-btn-flat-light tvd-right tva-delete-yes">
					<?php echo __( 'DELETE', TVA_Const::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>
