<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tva-input-field-editor">
	<div class="tvd-input-field">
		<input id="tva-item-title" type="text" placeholder="<#= placeholder #><?php echo __( ' Title', TVA_Const::T ) ?>" value="<#= model.get('post_title') #>" data-field="item_name">
		<label for="tva-item-title" class="tva-custom-label"></label>
	</div>
</div>