<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tva-ribbon-content">
	<div class="tva-ribbon">
		<?php echo __( 'It seems that your old version of Apprentice is still active. If you\'d like to disable it', TVA_Const::T ); ?>
		<a class="tva-disable-apprentice" href="javascript:void(0)"><strong><?php echo __( 'click here', TVA_Const::T ); ?></strong></a>.
	</div>
	<i class="tva-close-ribbon tvd-icon-close2 tvd-pointer"></i>
</div>