<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<span class="tva-subtitle">
	<?php echo __( 'Would you like to add a custom module cover image?', TVA_Const::T ) ?>
</span>
<div class="tva-main-cover-style">
	<div class="">
		<p class="tva-cover-img-title"><?php _e( 'Click to upload a cover image', TVA_Const::T ) ?></p>
		<p><?php _e( 'Recommended size:', TVA_Const::T ) ?> 1170 x 400px</p>
	</div>
</div>