<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tva-list tva-sendowl-list tva-sendowl-bundles-list" id="so_bundle">
	<a href="javascript:void(0)" class="tva-refresh-items tva-sendowl-button" data-type="bundles">
		<?php echo __( 'Refresh Bundles List', 'thrive-apprentice') ?>
	</a>
</div>
