<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="tva-list tva-sendowl-list tva-sendowl-products-list" id="so_product">
	<a href="javascript:void(0)" class="tva-refresh-items tva-sendowl-button" data-type="products">
		<?php echo __( 'Refresh Product List', TVA_Const::T ) ?>
	</a>
</div>
