<div class="tve_lg_input_container tve_lg_radio tve-draggable tve-droppable" draggable="true" data-columns="4">
	<p class="tve_lg_radio_label thrv-inline-text" data-group-editing-parent=".tve_lg_radio">
		<?php echo __( 'Radio Label', 'thrive-cb' ); ?>
	</p>
	<div class="tve-radio-grid">
		<div class="tve-radio-column" data-index="1">
			<div class="tve_lg_radio_wrapper" data-radio-style="default">
				<input type="radio" name="radio" data-label-value="true" value="Option A"/>
				<label></label>
				<span class="tve-checkmark"></span>
				<p class="tve-input-option-text"><?php echo __( 'Option A', 'thrive-cb' ); ?></p>
			</div>
		</div>
		<div class="tve-radio-column" data-index="2">
			<div class="tve_lg_radio_wrapper" data-radio-style="default">
				<input type="radio" name="radio" data-label-value="true" value="Option B"/>
				<label></label>
				<span class="tve-checkmark"></span>
				<p class="tve-input-option-text"><?php echo __( 'Option B', 'thrive-cb' ); ?></p>
			</div>
		</div>
		<div class="tve-radio-column" data-index="3">
			<div class="tve_lg_radio_wrapper" data-radio-style="default">
				<input name="radio" type="radio" data-label-value="true" value="Option C"/>
				<label></label>
				<span class="tve-checkmark"></span>
				<p class="tve-input-option-text"><?php echo __( 'Option C', 'thrive-cb' ); ?></p>
			</div>
		</div>
		<div class="tve-radio-column" data-index="4">
			<div class="tve_lg_radio_wrapper" data-radio-style="default">
				<input name="radio" type="radio" data-label-value="true" value="Option D"/>
				<label></label>
				<span class="tve-checkmark"></span>
				<p class="tve-input-option-text"><?php echo __( 'Option D', 'thrive-cb' ); ?></p>
			</div>
		</div>
	</div>
</div>