<div class="control-grid full-width pb-0">
	<span>
	<?php echo __( "At the moment we don't support custom fields integration for this Autoresponder or there are no custom fields available.", 'thrive-cb' ); ?>
	</span>
	<a class="blue-text" href="//thrivethemes.com/tkb_item/what-autoresponders-does-the-custom-field-integration-with-the-lead-generation-element-support/" target="_blank">
		<?php echo __( 'Learn more about this.', 'thrive-cb' ) ?>
	</a>
</div>